# Generated by Django 5.1.4 on 2024-12-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'permissions': [('can_add_modelname', 'Can add model'), ('can_change_modelname', 'Can change model'), ('can_delete_modelname', 'Can delete model')],
            },
        ),
    ]
